# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UseNode@1
  inputs:
    version: '20.x'
    checkLatest: true
  displayName: Use latest node version

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    npm run test
  displayName: 'Run tests'

- script: |
    ls -la $(System.DefaultWorkingDirectory)/coverage
  displayName: 'List files inside coverage directory'

- task: SonarCloudPrepare@4
  inputs:
    SonarQube: 'SonarCloud Connection'
    organization: 'frankdevops'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'FrankDevOps_Dodd400.git'
    cliProjectName: 'Dodd400.git'
    cliSources: './src'

- task: SonarCloudAnalyze@4
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@4
  inputs:
    pollingTimeoutSec: '300'

- task: PublishCodeCoverageResults@2
  inputs:
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    failIfCoverageEmpty: true
  displayName: 'Publish code coverage results'




