# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs: 
- job: A
  displayName: Build and install
  steps:
  - task: UseNode@1
    inputs:
      version: '20.x'
      checkLatest: true
    displayName: Use latest node version

  - script: |
      npm install
      npm run build
    displayName: 'npm install and build'



- job: B
  displayName: Publish Code Coverage
  dependsOn: A
  steps:
  - task: UseNode@1
    inputs:
      version: '20.x'
      checkLatest: true
    displayName: Use latest node version
  
  - script: |
      npm install
      npm run test
    displayName: 'npm install and run tests'

  - task: PublishCodeCoverageResults@2
    inputs:
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
      failIfCoverageEmpty: true
    displayName: 'Publish code coverage results'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/coverage'
      artifact: 'coverage_artifact'
      publishLocation: 'pipeline'


- job: 
  displayName: Publish Sonar results into SonarCloud
  dependsOn: B
  steps:
  - task: SonarCloudPrepare@4
    inputs:
      SonarQube: 'SonarCloud Connection'
      organization: 'frankdevops'
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: 'FrankDevOps_Dodd400.git'
      cliProjectName: 'Dodd400.git'
      cliSources: './src'

  - task: SonarCloudAnalyze@4
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'

  - task: SonarCloudPublish@4
    inputs:
      pollingTimeoutSec: '300'





